name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

publish_to: none

dependencies:
  circular_countdown:
    path: ../
  flutter:
    sdk: flutter
  gap: ^3.0.1
  timer_controller: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
